server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  redis:
    host: localhost
    port: 6379
    global-lock-name: updateExchangeRateLock;

api-layer:
  base-url: http://apilayer.net/api/live
  access-key: cfaf3ffe448afdc96e9b4b2b48c4b571
  allowed-sources: USD
  allowed-targets: KRW,JPY,PHP

